FROM ghcr.io/k8s-at-home/prowlarr:v0.4.0.1765@sha256:d306f3e4986df6f3940f53cead75b97dcae63932e23fa6073fa7c89f9db57f73
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
