FROM ghcr.io/k8s-at-home/prowlarr:v0.4.0.1769@sha256:ebf209474f79af5feb569e5cde74452fb6dbc26bfacf76df5f301eac99f2b13e
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
