FROM ghcr.io/linuxserver/projectsend:2021.12.10@sha256:db84505b03d252dae254353c86a1fd04aef91cd68a8aed3f2882d7a4a413d976
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
