FROM homeassistant/home-assistant:2021.12.8@sha256:81d381f5008c082a37da97d8b08dd8b358dae7ecf49e62ce3ef1eeaefc4381bb

LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
