FROM homeassistant/home-assistant:2021.12.5@sha256:62fbbccd89595ea312d23ceee15fed2924eff4da787110c3a048692f47ac111d

LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
