# hadolint disable=DL3007
FROM reallibrephotos/librephotos:latest@sha256:28e518231afa0273d8d8f2f8ff59851f2a44cf1caeaec6ad311a520766e5afac
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
