FROM ghcr.io/nicholaswilde/odoo:version-14.0@sha256:7cff9672ce078f7e2cf132625f0bc0fa68e932955d23e2e8c2ce7c235d5c5f8d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
