FROM ghcr.io/linuxserver/filezilla:version-3.51.0-r1@sha256:5103cdd266ceb61cebabae6629e418570a5094e3f61ef2f405f6e24d4fc7f6a4
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
