FROM ghcr.io/linuxserver/bookstack:22.04.20220429@sha256:ee35cdbb7de64cab7c8cdee3c4b0f42861831e93fd7fdeb9398f8caddc083eb4
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
