FROM ghcr.io/linuxserver/bookstack:21.12.20211223@sha256:f05447347ff102589c7db6f51ff07a2717c6a8cb2bd557a8b4ffa27ef1cefc7a
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
