FROM ghcr.io/k8s-at-home/haste-server:latest@sha256:827aa2f2389d94a522e333080fa8cbc0e0a487c5681173caca785b3b6b9e5b01
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
