FROM ghcr.io/linuxserver/beets:version-1.5.0@sha256:5bdb3a8ed128aab4744825fd9657a754632baba5f6d9ae84fa88ac27ed0fa75f
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
