FROM ghcr.io/linuxserver/beets:version-1.6.0@sha256:bc5016e84e9ad5664d52fbc0c22e679cfbce7ae31c287cf65ec6f6645fe0f8e7
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
