FROM ghcr.io/linuxserver/booksonic-air:2201.1.0@sha256:3a0d8a2de1be66dac1ddcd7a881258c6743a32596b9df829988c2239eb5ef7ee
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
