FROM ghcr.io/linuxserver/booksonic-air:version-v2009.1.0@sha256:ca74f3d0f0a4165f9ffaa3733274b5c14817ff977d04426ba71435c51b110d19
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
