FROM ghcr.io/k8s-at-home/apache-musicindex:v1.4.1-2@sha256:c8b5cf5fbf4bbf097fb516f82bfc3ecb1ad971e8059dc9722b4d10bb7d7faee7
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
