FROM ghcr.io/techno-tim/littlelink-server:latest@sha256:589ce9970228588fa965c79c65a769bad9eaf666c4bbd42ea15dc9353c254856
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
