FROM ghcr.io/techno-tim/littlelink-server:latest@sha256:6e1614ed9dd2cd6a2f40f882a744f7ed7a0db894b660691226d190a200571049
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
