FROM ghcr.io/techno-tim/littlelink-server:latest@sha256:e3fcc14dc00bf5fe37fbfc90bf96c85f1d2083483cbbeaa38a534be2422e7230
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
