FROM ghcr.io/linuxserver/remmina:version-1.2.0-rcgit.29dfsg-1ubuntu1@sha256:9667a77b467adf575efd8171395d7e26688d3436e9ca5edf2f52195a73b40b69
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
