FROM ghcr.io/linuxserver/remmina:version-1.2.0-rcgit.29dfsg-1ubuntu1@sha256:ea7c1374dc2a9936b5cb41b40c1ac273988169ebf7c6937a7664cdf697d08461
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
