FROM ghcr.io/linuxserver/remmina:version-1.2.0-rcgit.29dfsg-1ubuntu1@sha256:72daa26acbc9f3430366246c487e65d81fca647e14e73b5e006bf9f00209faba
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
