FROM ghcr.io/linuxserver/heimdall:version-2.2.2@sha256:315ddeb45c09f79fba5aae1a172d31eedc386d6a96505f5eedc4442564dc7285
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
