FROM ghcr.io/linuxserver/heimdall:version-2.2.2@sha256:2155bb4093358e207af60d9bd44e46e4203fc80addd7ff0f542c9b4927ef2439
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
