FROM ghcr.io/linuxserver/heimdall:version-2.2.2@sha256:3ccfe72758c7da1be485b74c77cceb82b234b1045257328b04070c067a42b504
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
