FROM ghcr.io/linuxserver/grocy:version-v3.1.1@sha256:f67e4ce1c7498f5360d874955b0baf3b6b4ae88f5411094d32f7bfb93ddd4a5a
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
