FROM ghcr.io/linuxserver/mysql-workbench:8.0.28@sha256:af8b906df9d00cf1f984764fad2965fe36b5e485a969555bb389fdb415a8efce
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
