FROM ghcr.io/linuxserver/mysql-workbench:8.0.27@sha256:457d54936953a80b187d12c5b8008ed7cfbeeedc86dcb6dea0f70c5a147f6e65
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
