FROM ghcr.io/linuxserver/mysql-workbench:8.0.28@sha256:2ebe75973cc00000e54e1d1f91bbe1c0cf96e6aed3990cc2c6675b23966c5004
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
