FROM ghcr.io/linuxserver/smokeping:version-2.7.3-r5@sha256:a0015ca40d3fa80644a47f2fc9fb6af197d30583c0c2009f1e854f5af38c6803
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
