FROM ghcr.io/linuxserver/smokeping:version-2.7.3-r5@sha256:6cdd4b202624c346bd047631061e9eccaad59bd2347d130e16fe8553b677b7b0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
