FROM ghcr.io/linuxserver/scrutiny:2021.11.18@sha256:c43d3d40e9deaddb564bc54d1ae071994b0ce78af8c3a11b228d1450899bc4d3
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
