FROM pmaksymiuk/icantbelieveitsnotvaletudo:2021.2.1@sha256:cfb6ca812b7bec09ef61d60c8ab71945b6594525673f2edd9ddcd88004d8b150
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
