FROM tinymediamanager/tinymediamanager:4.2.7@sha256:80602caa61aea1f274265af9a8e3e90722d18f2d191b586d9304ada590e9d334
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
