FROM tinymediamanager/tinymediamanager:4.2.8@sha256:f0ae059f0810fe7a993a57351fae00c42ec62370d2243fdcc0d424c3bb441884
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
