COMPANY_NAME=onlyoffice
GIT_BRANCH=develop
PRODUCT_NAME=documentserver-ie
ONLYOFFICE_VALUE=onlyoffice
RELEASE_BRANCH=origin
PRODUCT_VERSION=7.0.0
BUILD_NUMBER=132
S3_BUCKET=repo-doc-onlyoffice-com
PACKAGE_NAME="${COMPANY_NAME}-${PRODUCT_NAME}"

PACKAGE_VERSION="${PRODUCT_VERSION}-${BUILD_NUMBER}"

echo "http://${S3_BUCKET}.s3-eu-west-1.amazonaws.com/centos/7/${COMPANY_NAME}-${PRODUCT_NAME}/${GIT_BRANCH}/${PACKAGE_VERSION}/${COMPANY_NAME}-${PRODUCT_NAME}-${PACKAGE_VERSION}.x86_64.rpm"



echo "http://${S3_BUCKET}.s3.amazonaws.com/${COMPANY_NAME}/${RELEASE_BRANCH}/ubuntu/${PACKAGE_NAME}_${PACKAGE_VERSION}_amd64.deb"