FROM ghcr.io/nicholaswilde/etherpad:version-1.8.14@sha256:26bbd45110d5b4d70246fafe40d4c4a7047b7b4fde409763a125324fa93b2d73
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
