FROM ghcr.io/nicholaswilde/golinks:version-154c581@sha256:8e67b26324c5dc433210df8f2fb64317db3cbbe7db0b9e10c6e5bc3f3f7860e4
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
