FROM ghcr.io/nicholaswilde/shorturl:version-v0.1.0@sha256:75fc450af5d2d07e5caebc6a01863a0aacdc15c1fbe57b3db46e3bd548226420
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
