FROM airsonicadvanced/airsonic-advanced:edge-11.0.0-SNAPSHOT.20220109073049@sha256:cbbd94cb4a8367f78e8e5e2f84a42732421c9c21eab7dc248cbb0b4dcd2b51f1
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
