FROM ghcr.io/linuxserver/librespeed:version-5.2.4@sha256:98a529a7081d97aadbe4c482358fd534cc6047b31041a0c8bb8c7f2fd2e51cd5
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
