FROM ghcr.io/linuxserver/librespeed:version-5.2.4@sha256:1d6f31c593df5e9e169430e21c7bad3bf0bed87a95027c542d45480a4100b1c6
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
