FROM ghcr.io/linuxserver/librespeed:version-5.2.4@sha256:c5d9283f35dcf6209ff818ed0b90d75421c996c9126d1795d7c132d2ae9bbb97
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
