FROM ghcr.io/nicholaswilde/wiki:version-900b76a@sha256:6c4f261d8f5e5dadd5ec97465465d434dc6730a85ccf9af415c03d1c0e8d1afd
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
FROM requarks/wiki:2.5@sha256:b4856c5562c21cf93407a6068363967bc0fb6f44fb8022f4f7567a303ad232db
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
