FROM ghcr.io/nicholaswilde/wiki:version-900b76a@sha256:6c4f261d8f5e5dadd5ec97465465d434dc6730a85ccf9af415c03d1c0e8d1afd
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
FROM requarks/wiki:2.5@sha256:4241796c343106f89fdc585229993df05c0ae81bdbbfc13a6f6a5be9b23d662e
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
