FROM ghcr.io/nicholaswilde/wiki:version-900b76a@sha256:6c4f261d8f5e5dadd5ec97465465d434dc6730a85ccf9af415c03d1c0e8d1afd
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
FROM requarks/wiki:2.5@sha256:4d96ecb09ed6c3b2df483ba0c3b24e37df6ff1049171e6efcc4a1c0f39c2d502
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
