FROM ghcr.io/miguelndecarvalho/speedtest-exporter:v3.4.3@sha256:09b532e16c80d0db3fd63aacda087203857a23f12d4ff1e7a093d10f331523e1
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
