FROM ghcr.io/miguelndecarvalho/speedtest-exporter:v3.4.1@sha256:087646ccf49057d5380c2d74c05824162f89d389268da4dfab4fca9ac6bab6b1
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
