FROM ghcr.io/miguelndecarvalho/speedtest-exporter:v3.3.4@sha256:e8323a0195d26f2409f3e9812a48a3a4cc9a70bb79b7b6195398ae0c1fd3a8f0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
