FROM ghcr.io/linuxserver/htpcmanager:2021.11.17@sha256:846220a9512e9a91bdd7d7808b2ddd1f4e25b4ed9e72a31a7aeabbdd2e36f46d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
