FROM reallibrephotos/librephotos-frontend:latest@sha256:f0ba2b961204fde6ded3c9c5dadfaa4a60efd6c129809f56c6ceaa3029be8bfa
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
