FROM reallibrephotos/librephotos-frontend:latest@sha256:461d912f4a1a1de4ea870f655cf322da08c703a458c05d221c55940cbb96cea0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
