FROM reallibrephotos/librephotos-frontend:latest@sha256:68bf6130b6d380528b3fe48bfa7ee8606e34e7066b30268965b4176fafef297e
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
