FROM ghcr.io/linuxserver/sqlitebrowser:3.12.2@sha256:426e79828c4b8a381f2265da3e3556edc996e0aeef6d55fb8ab108daa203a234
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
