FROM ghcr.io/linuxserver/grav:version-1.7.18@sha256:e4fc1032fd78c0a6772cf141669449fdd4d0f5e6ad4646d6ebaf0b6015631738
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
