FROM ghcr.io/linuxserver/photoshow:version-48aabb98@sha256:25a1427db9dc5d133878bbbf39e59eb554f88a09ad81f01583d71190d2808448
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
