FROM ghcr.io/linuxserver/photoshow:version-48aabb98@sha256:573f2c7a1bd951f13a3bac6282c0bc112a89d840b050e6d137c79049425d6847
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
