FROM ghcr.io/linuxserver/photoshow:version-48aabb98@sha256:97b515e22bc05511a16554d8857662d4b3df2b59980b79cc4b0b04a5dce3b1a8
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
