FROM browserless/chrome:1.51.1-chrome-stable@sha256:3f77e6e1ced6d7f9afbaf835c155956a793bd9825dac27c516b46c64e1118e11
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
