FROM ghcr.io/nicholaswilde/novnc:version-1.2.0@sha256:5d0d02fa11dabb607ddf293b3b3794ef15f2a9b32e41078de5ed24ad3cfad095
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
