FROM ghcr.io/linuxserver/doublecommander:version-0.8.2-1@sha256:d92969a929c24ae5948e7c9ea53994cb0dc7704250a6d983aefeda3182209b0d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
