FROM ghcr.io/linuxserver/doublecommander:0.9.8@sha256:aed62ac83baa94f7d963829fd4731c3c0db695c120f20dcbbd2a849495302728
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
