FROM ghcr.io/linuxserver/resilio-sync:version-2.7.2.1375@sha256:605b6d54402830fddfbadcdc8e12ab57015743a889e2f0a02641c8601afa42ba
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
