FROM zabbix/zabbix-web-nginx-pgsql:ubuntu-6.0.3@sha256:8e738b5fd231b745d30d3c52355b6bfe0afc7ef824bd8542ef2dbf1cd0b0f283
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
