FROM zabbix/zabbix-web-nginx-pgsql:ubuntu-6.0.4@sha256:7aaeebd924c355bc439040a8911e58f940f13c927e57502af84252ed972ae458
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
