FROM ghcr.io/linuxserver/dokuwiki:2021.11.28@sha256:441a75ea0a697391a0b087fe8e0bb317b4cbe54c989625ec5baf9d5d676926bb
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
