FROM ghcr.io/nicholaswilde/fossil:2.15.1-ls4@sha256:a0a819ed2707e8e829dec371de0e166fbcf0499d3d12005880f603b2b95bf64d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
