FROM ghcr.io/linuxserver/oscam:version-11693@sha256:e97f9929c3a6caed6ee24ed9f1efdd4a8c29b4b2ba52205d3f8daebdaf7a9ea2
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
