FROM ghcr.io/linuxserver/lazylibrarian:latest@sha256:1e8fb03b12e0f440d0b8ea4a5ed5746a64b82bead53cf09920c5617c4683cf78
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
