FROM ghcr.io/linuxserver/lazylibrarian:latest@sha256:4e40c7f99324f78f05e3678bebce2239bbf67a964b7c08f1e09d1ea7bcb44a0c
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
