FROM ghcr.io/linuxserver/lazylibrarian:latest@sha256:36bac1de9363761bafb2d7695312f330cc12a57f78eb43ca53be32c5d8761a25
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
