FROM ghcr.io/nicholaswilde/shiori:version-v1.5.0@sha256:e0645abe677786f79bde80ac81f8d79c915e05cba2991c4cecd335f54335431c
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
