FROM ghcr.io/nicholaswilde/leantime:2.1.7-ls6@sha256:60e3485f98d71f814f593c1c4d39cac78fc2748f7a1a4baacbbfa439ae031237
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
