FROM ghcr.io/linuxserver/piwigo:version-11.5.0@sha256:13aa1206583cf5ff5d20c6d9b0738bcf5de6907b27e96c334ff5e3b716e959d9
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
