FROM docker:20.10.14-dind@sha256:de2946cebcffd99a249578e56de6df20c9603823cae69516e80d8695b768f952

RUN apk update && apk add nano docker-compose curl bash

LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
