FROM ghcr.io/linuxserver/freshrss:version-1.18.1@sha256:71de55d655505f28d7d6d2c7e45ee07c2db2641b64cffe226e77dc0452984ca3
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
