FROM ghcr.io/linuxserver/freshrss:version-1.18.1@sha256:12d5889d3a92cd6e493c44b9b5aa4f05aafbf7236ad5cd0a8b8e357fe6836f88
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
