FROM billimek/prometheus-uptimerobot-exporter:0.0.1@sha256:f14ccd7aad0e0ef19dc5c5c359b0921030a769e2505acec5b913d749281327be
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
