FROM ghcr.io/deconz-community/deconz-docker:v2.13.02@sha256:ed4a88ee75eeaf04155c3e733cf38011247139ed265d178b67ddde46889eca8c
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
