FROM ghcr.io/k8s-at-home/readarr:v0.1.0.1160@sha256:bc9ade6d527545b525711d8d9d58cfc819403ad215beec4a6552f3555cdb9b1e
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
