FROM ghcr.io/k8s-at-home/readarr:v0.1.0.1142@sha256:b9ae6af4ed5041dd26a575bd02adedc25206d281f7fbf06020d1d74c8515a1a2
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
