FROM ghcr.io/linuxserver/minisatip:2021.12.01@sha256:d252018c680acedebb91a7b5cc87c2c3d74bb1ee0323b57f5a322b9f40a5969b
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
