FROM ghcr.io/linuxserver/deluge:version-2.0.5-r0@sha256:14b3ba4165e46f04150a31489bd8e2f3a1032c5999f9bb9ef7b3f1385b513690
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
