FROM ghcr.io/linuxserver/deluge:version-2.0.5-r0@sha256:8688b62f3f63a61a40460bf1307d60f2d58e9ff2074a0310ca47ec66ef3889ec
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
