FROM storjlabs/storagenode:f939e10c9-v1.53.1-go1.17.5@sha256:eca53f6c95198afadb21bd39b3c88e7a6bca692c5b8ce28a646d96d864d9ab08
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
