FROM browserless/chrome:1.52.0-chrome-stable@sha256:140e30d0c389b0c6af511edc680badf0262936b90db07198bb992060d9549f0e
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
