FROM browserless/chrome:1.53.0-chrome-stable@sha256:50a39d7d656483ce9f206a6178a1d59d75f8b5d86a2602a8eb084823fdfd68e7
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
