FROM browserless/chrome:1.52.1-chrome-stable@sha256:935f2cde1029870f1691af28c4194dd4166f58b1c11114dfe6959ee86f0cf406
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
