FROM ghcr.io/paperless-ngx/paperless-ngx:1.6.0@sha256:f2f2d77cb7898a338314a59103b1b403807a7fa479b78489edb0ebb8de477d15
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
