FROM ghcr.io/paperless-ngx/paperless-ngx:1.5.0@sha256:b61d514e178ddfa4673e72d0440b3166d46ec977dc6bbc7a9a293adf64200f55
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
