FROM ghcr.io/paperless-ngx/paperless-ngx:1.7.0@sha256:3b836aeac06f68176db841d8a214a760ec841a1c0cf811570ecba48e17e7c764
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
