FROM registry.gitlab.com/bockiii/deemix-docker:latest@sha256:8b000a7ad08ecd018a758eefaa4c29c8d7f247be54d4d35454ffb4f36a735bc0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
