FROM registry.gitlab.com/bockiii/deemix-docker:latest@sha256:a5c84ede260b64b4bd512a52e7ae28a178ca37eb6575c912ffc5fbaf7cb26e7f
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
