FROM registry.gitlab.com/bockiii/deemix-docker:latest@sha256:c38cf91d6c069630359e4368ef7f1a56b7d1df37893c87f3e3c59aaef05db2d0
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
