FROM ghcr.io/linuxserver/sickchill:2022.2.20@sha256:a4a6d35e30238ba5b2aa97802ec48361b0e667dbf816f2f1af00ed312ac3683d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
