FROM ghcr.io/linuxserver/pyload:version-5de90278@sha256:d3c87933a5fd8c67a7add40706e0042ad229c9a47cd1bc7ba3953b8ad049a6ce
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
