FROM ghcr.io/linuxserver/foldingathome:7.6.21@sha256:5b6dc35c16c436ca3e00ccdf60826bc9148013b7c7dc0243fb002de99bec02ec
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
