FROM ghcr.io/linuxserver/foldingathome:7.6.21@sha256:ec72ee41ab4c69ce7be2fc93f1e17a3d4f66c3fc79621f8280866451bbf54efe
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
