FROM ghcr.io/linuxserver/headphones:version-58edc604@sha256:43f2d40be460ac59c6b80d6ea1307f14dad11379ac607b6752f84a758da6b118
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
