FROM ghcr.io/linuxserver/calibre:v5.34.0-ls143@sha256:3c8742bed36b9c65d5914327ef7f9ed3143fdd51957b656cfe2fa2b38e98ad53
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
