FROM ghcr.io/linuxserver/calibre:v5.34.0-ls141@sha256:0da52a11363f13d6c304f2b575df1ae5db5fcbf389b9d76cabfd372a71de1776
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
