# hadolint ignore=DL3007
FROM randomninjaatk/amd:latest@sha256:9d0cf8206966456e065a1ded124b28dd0fb6172c5e6ded082e10788cfcadb24f
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
