FROM ghcr.io/linuxserver/mstream:version-v5.2.5@sha256:22c012bcc43cde544532e7797da678ffd0dab76d3afeec0a2906adfae6767256
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
