FROM ghcr.io/linuxserver/quassel-core:0.14.0@sha256:95081d6a1ba1744d885fc6f407b809891a6abed64f00dc4fd6994c7a3c201846
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
