FROM ghcr.io/linuxserver/quassel-core:0.14.0@sha256:c583da2cb68c7fcbe0aa7306bf65a54e7427047d20eea28e40c6ea1a780ce2d7
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
