FROM ghcr.io/linuxserver/muximux:version-057352e8@sha256:7d7ee8fe58ccd1a6a11b47babd2ed1d3dc2cb2c6f83832dedfbaee0630814b30
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
