FROM ghcr.io/linuxserver/muximux:version-057352e8@sha256:df34cfce767f8b6bd90caf929c8ef32cefcdbb1b1a5d66632b5eb563028b1a64
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
