FROM ghcr.io/linuxserver/muximux:version-057352e8@sha256:cef1d47aadc2159cc2a63cc25f616497139f71085cf465eb0299cbab9377ee6d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
