FROM ghcr.io/linuxserver/digikam:version-7.3.0@sha256:8bcf6454a149de8920c43a845321ad981206e2b10d0c8a1fad1d763e80e53d97
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
