FROM ghcr.io/linuxserver/digikam:version-7.3.0@sha256:55b4c7f320aed3a4f08018404b1e2c276ea31bb39342647ce7f480e676d01450
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
