FROM ghcr.io/crazy-max/firefox-syncserver:1.8.0@sha256:ab1a959d8105c478f0f1523c8c3bbdc53bb8d44f325501b93297bc80cf627da6
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
