FROM docker.io/gangefors/airdcpp-webclient:2.11.2@sha256:2b3eb50f1bdc537d887bacee6e815cb0b4fb6c53bac723b3267f3c4d13a22274
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
