FROM ghcr.io/linuxserver/sickgear:version-release_0.25.26@sha256:d0a88e523169a9735d8dd23184f8995e1786ebcf86190f16506233ba3fdc15a3
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
