FROM ghcr.io/linuxserver/sickgear:version-release_0.25.26@sha256:80b39cff65c61ff30398cf5562a90d3e20441b0af05da2f9b3034a2e2fbae126
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
