FROM ghcr.io/linuxserver/sickgear:version-release_0.25.26@sha256:32e29b93363ff5f16af7242722bab4250b591df116b65fe9b079b44dbe7c1f40
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
