FROM ghcr.io/linuxserver/mylar3:version-v0.6.3@sha256:0f0b11ec0cd2d6e7ef89eda7d81b06aeb796bc6e2d2b216858bad8e45bb8e98a
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
