FROM ghcr.io/linuxserver/mylar3:version-v0.5.3@sha256:b96f0e97ab3f4bf4e4320670aa932d0f7df39d1ddce0bbf62808bd509209d78f
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
