FROM ghcr.io/linuxserver/mylar3:version-v0.6.3@sha256:fb148aa9c6d5d639eb2762b638e07d95aa65e5ba1143759b3e8c13a5764f35fc
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
