FROM zabbix/zabbix-server-pgsql:ubuntu-6.0.3@sha256:57c7029b899d5e11c12ade03b7d68a16955723ccd4ff1af9fc54e99681315774
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
