FROM zabbix/zabbix-server-pgsql:ubuntu-6.0.4@sha256:29a4a0d9878a651cb735a1534dfe42a9efceb9a4f75b788954065bf68b6c287e
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
