FROM ghcr.io/linuxserver/nntp2nntp:0.3.20211116@sha256:0ffb384bc893bc8c1aa5dcbd63d6aff28766bb992e23e5805ae0ebb2d7295faf
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
