FROM ghcr.io/linuxserver/airsonic:version-v10.6.2@sha256:1d585ffaf6fbde2e1d95cc13e14811ba31fe479bccab721c34dd7080fd5d6b53
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
