FROM ghcr.io/linuxserver/airsonic:version-v10.6.2@sha256:7bf80502d906a7c4a35aa1e9d13a16514c7369d26652f62ee6377f51c9bc7bc2
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
