FROM ghcr.io/linuxserver/airsonic:version-v10.6.2@sha256:8b42de38222839c0ff8914479853cfd5e4a8160d81c9a9ef6e9896be6629bf29
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
