FROM ghcr.io/linuxserver/nano-wallet:2021.12.16@sha256:fdac02e669290b9cec33f2610ba9c8159ebfc59c9996222231b0deed26e701ee
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
