FROM ghcr.io/linuxserver/endlessh:2021.11.21@sha256:d1f67963c18ccfc995338c96276ec7563ff5661ddd3cd2ecd554b0c8526ea1a9
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
