FROM reallibrephotos/librephotos-proxy:latest@sha256:78cd336af2b5e8d1a631b861245697f746ccfe655dff786a6598bed1d20c041c
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
