FROM reallibrephotos/librephotos-proxy:latest@sha256:fdb8c35eb606ee9cb31809be4dc1b567e376d03984f91b421cefd90d138b9dd3
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
