FROM reallibrephotos/librephotos-proxy:latest@sha256:237d5f6e582572fe799ccf9b1ed3e620acdcee34f3b125b931d091e196ea3b83
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
