FROM ghcr.io/linuxserver/openvscode-server:1.63.2@sha256:d152f5713fa52152d044b03fa1bd302056714963adbdfa561f11685733ae376b
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
