FROM ghcr.io/linuxserver/openvscode-server:1.66.0@sha256:91b5ba6a6d3271cabe27a52b76fc98f93389817bba32bcaa685cd26b7ccc9169
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
