FROM ghcr.io/linuxserver/openvscode-server:1.63.0@sha256:5ea6283eb78f476dfc0593bf2f1bf148b787bc8c92f71a1066433dfef5362bf1
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
