FROM ghcr.io/linuxserver/limnoria:2021.11.20@sha256:501732eefd3fea1409ba948f6ae2126655f842ffdc40a102bd5bdfb85760c9e7
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
