FROM ghcr.io/linuxserver/cloud9:version-1.29.2@sha256:67a012623b39e8cf62e3646f2537d5afc5ad4c61918acd626ae1f39adbecbe05
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
