FROM ghcr.io/flaresolverr/flaresolverr:v2.2.2@sha256:df1292a6218f1c4e1801978e89ebfe6fdea09d132e0cea2402c91b04a7f3706d
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
