FROM ghcr.io/flaresolverr/flaresolverr:v2.2.4@sha256:385eda4072fd3a7352c6e967613ac2c0d4860078bcafb8e8ab6c7c88ef4e16a9
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
