FROM ghcr.io/flaresolverr/flaresolverr:v2.1.0@sha256:8cf8a216ae7ec082ce31c6b397fc6b0357780630d7d8fbbdd4845154cc8df30b
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
