FROM docker.io/filebrowser/filebrowser:v2.21.1@sha256:fc69202b56e8a883a152f54467e4d8e5a3ed75b7ffb78a33aef63e222b46f773
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
