FROM docker.io/filebrowser/filebrowser:v2.21.1@sha256:e1f43b1b8a1acb1d7cd5f934454e7a2ef571ea3bab48b0e1ed0fa97ef9df8d69
LABEL "org.opencontainers.image.source"="https://github.com/truecharts/containers"
